export const TIMER = {
  START: 'TIMER/START',
  SET: 'TIMER/SET/ID',
  TICK: 'TIMER/TICK',
  END: 'TIMER/END',
  STATUS: {
    WORKING: 'WORKING',
    UNWORKING: 'UNWORKING',
  },
};

export const ELEVATOR = {
  MOVING_TO: {
    TOP: 'ELEVATOR/MOVING_TO/TOP',
    BOTTOM: 'ELEVATOR/MOVING_TO/BOTTOM',
    STAYING: 'ELEVATOR/MOVING_TO/STAYING',
  },
  FLOOR: {
    CLICK: 'ELEVATOR/FLOOR/CLICK',
  },
  CHANGE_STATUS: 'ELEVATOR/CHANGE_STATUS',
};

export const QUEUE = {
  ADD: 'QUEUE/ADD',
};
